[book]
authors = ["Cameron Dugan"]
language = "en"
src = "src"
title = "CameronDugan.com"
description = "A Personal Website by Cameron Dugan"

[preprocessor.reading-time]
words-per-minute = 180
[preprocessor.external-links]
after = ["rss"]
renderers = ["html"]

[preprocessor.rss]
renderers = ["html"]
files-glob = "*/*.md" # blog/*.md or projects/*.md
url-base = "https://camerondugan.com/"

[build]
create-missing = false # my editor can create the file from md ref

[output.linkcheck]

[output.html]
preferred-dark-theme = "ayu"
no-section-label = true
git-repository-url = "https://github.com/camerondugan/camerondugan.book"
# edit-url-template = "https://github.com/camerondugan/camerondugan.book/edit/main/{path}"

[output.html.redirect]
