[book]
authors = ["Cameron Dugan"]
language = "en"
src = "src"
title = "CameronDugan.com"
description = "A Personal Website by Cameron Dugan"

[preprocessor.reading-time]
words-per-minute = 180
renderers = ["html", "tiny"]

[preprocessor.external-links]
after = ["rss"]
renderers = ["html", "tiny"]

[preprocessor.rss]
renderers = ["html", "tiny"]
files-glob = "*/*.md" # blog/*.md or projects/*.md
url-base = "https://camerondugan.com/"

[build]
create-missing = false # my editor can create the file from md ref

[output.linkcheck]

[output.html]
smart-punctuation = true
preferred-dark-theme = "ayu"
no-section-label = true
git-repository-url = "https://github.com/camerondugan/camerondugan.book"
git-repository-icon = "fa-code-fork"
edit-url-template = "https://github.com/camerondugan/camerondugan.book/edit/main/{path}"

[output.html.redirect]

[output.tiny]
# # relative to your src folder
css-paths = ["css/simple.css"]
nav-separator = " - "
index = "getting-started.md" # Home tab
extra-nav.Contact = "contact.md"
# extra-nav.GettingStarted= "getting-started.md"
extra-nav.Projects = "projects.md"
extra-nav.Blog = "blog.md"
# extra-nav.Mirror = "https://book.camerondugan.com"
# extra-nav.Contact= "contact.md"
